name: flutter_app1
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
   sdk: flutter
  moor: ^4.6.1+1
  sqlite3_flutter_libs: ^0.5.4
  path_provider: ^2.0.9
  path: ^1.7.0
  http: ^0.13.4
  url_launcher: ^5.4.11
  
  #SharedPreference-persisting theme selection
  shared_preferences: ^2.0.13

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  moor_generator: ^4.6.0+1

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets: 
   - assets/images/

fonts:
 - family: Pangolin
   fonts:
    - asset: assets/fonts/Pangolin-Regular.ttf

